# yamllint disable rule:line-length
---
sudo: required

language: rust

matrix:
  include:
    - os: linux
    - os: windows
    - os: osx
      osx_image: xcode11

cache:
  cargo: true

script:
  - ./scripts/travis.sh

_github_api_key: &_github_api_key
  api_key:
    secure: "UZOLAQ+p1UCOdIGYU40/wq3SgoqbjQOst6gNQrjUPmWLQKcxuaNxBh/OajH1YD/kbVaW4lHKtpdKASg48HVEZlY9ku5rL1zXzVMYMaCfwA+KQvq7DkWI2R+uWs69XoaoeJKVp5zXRpIr24J4I/0/OHkB/jCiAdVe15LwraiJNBoR6L19xunRdfL7pzvveb0N+4Td5yckfziLi7EwvMjtFjZ0gN94QObtl5XOjGzt233cQqoDfjqmDxc6Ac0K5FyOOivdpcHipuAcz4TLAjgS4rO4zh4PpDSNE2nKO7xdyL7149afc6LtOJcZ96Kun6pbC/cUy4zXobZwtToiSRmoJP3jWhyZLjp4CPSXODrjdMRB0+d2vpw2RXaTVCn1PccKx+BB4NXjfiFWAAIPIEW1O4tFre8082P/9degFjuJcHcmdh8499gPT/hp8yoo8I7hkoYeCyuirC9BzC/WKbp8R4YglYZoWtQ71NqfGYVgYMoi2Zmd/le6dQ62lpV51B5W+dRp3HqV+Ws39yEnU16V8Io/v4XxkF/QScYoaWYc0GS+NwZluPDlxv8x5LShAwLksRcteQBNvLRxMtXZ1GvkXlowCymj0DYlAPFLxhniHESb/MrlkASwglgRi7lyslDx4sedHPejvWaMTjwn2lkbRojxR0J2GIicIjR8Dy0HX5Y="

deploy:
  - provider: releases
    file_glob: true
    file: "yamllint.exe"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = windows"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "yamllint"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "yamllint"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    <<: *_github_api_key
...
