FROM ekidd/rust-musl-builder:stable

RUN sudo apt-get update && \
    sudo apt-get install -y software-properties-common && \
    sudo add-apt-repository -y ppa:deadsnakes/ppa && \
    sudo apt-get install -y python3.8-dev && \
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 2

ENV USER=rust
ENV JEMALLOC_SYS_DISABLE_SHARED=1

WORKDIR /work

# vim: ft=dockerfile:
